### ISSUE TITLE
Add Cargo.lock file to be able to build from tags

### ISSUE THREAD

**Issue by theanurin** [tonlabs/tonos-cli#166]
[Cargo.lock](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) is a special file to lock versions of dependency libraries.

Without this file there no way do build oldest tags/commits due dependency libraries make API changes.

Is there any reason why Cargo.lock is missing?

References:
- https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
- https://github.com/rust-lang/cargo/issues/315

**Comment by theanurin** [comment]
### Right now

For example, I downloaded https://github.com/tonlabs/tonos-cli/archive/refs/tags/v0.13.0.tar.gz and trying to build by ```cargo build --release -j1```

The build is failed.
Looks like latest ton-labs-types@388a833 is broken. And using `Cargo.lock` we can point to right commit of ton-labs-types (not latest).

Of course, my build problem may be environment specific, but this is different situation (not related to missing `Cargo.lock` file)

### References:
#### Output:
```
   ...
   Compiling api_info v1.15.0 (https://github.com/tonlabs/TON-SDK.git#1a12fda2)
   Compiling ton_client v1.15.0 (https://github.com/tonlabs/TON-SDK.git#1a12fda2)
   Compiling futures v0.3.15
   Compiling h2 v0.2.7
error[E0277]: the trait bound `[u8; 32]: std::convert::From<std::vec::Vec<u8>>` is not satisfied
   --> /root/.cargo/git/checkouts/ton-labs-types-44487be4b4f492ad/388a833/src/types.rs:130:17
    |
130 |         Ok(Self(bytes.try_into().unwrap()))
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::vec::Vec<u8>>` is not implemented for `[u8; 32]`
    ...
```

**Comment by theanurin** [comment]
I made some research and I can confirm that `Cargo.lock` make right behaviour.

1) I made sanity checker build via GitHub Actions to reproduce the issue with [broken build](https://github.com/cexiolabs/tonos-cli/runs/2646357221?check_suite_focus=true#step:3:539). Here we can see that build on tag v0.13.0 is broken right now
2) I made commit that adds `Cargo.lock` (with lock to TON-SDK 1.14.1) and this is repaired the [build](https://github.com/cexiolabs/tonos-cli/runs/2646527672?check_suite_focus=true)
 
 If my contribution make sense, I will create PR.
 Thanks, and what for feedback.
 
<img width="800" alt="Screenshot 2021-05-22 at 19 31 38" src="https://user-images.githubusercontent.com/22301243/119234429-8a6d9e80-bb36-11eb-9aa6-a1a5ac4ff287.png">
